version: '3.9'

services:
  pds:
    image: ghcr.io/bluesky-social/pds:0.4
    container_name: pds
    restart: unless-stopped
    volumes:
      - data:/pds

  pdsadmin:
    image: ghcr.io/cr0ssing/pdsadmin-docker
    container_name: pdsadmin
    restart: unless-stopped
    volumes:
      - data:/pds

volumes:
  data:
